### ISSUE TITLE
Bug ở train_per_iter() 🚑️

### ISSUE THREAD

**Issue by Bonkaaa** [Bonkaaa/Code_review_generation#2]
🐛 Bug khi chạy model
```
line 18, in train_per_iter
TypeError: string indices must be integers, not 'str'
    in_ids = data['source_ids'].to(DEVICE)
                 ~~~^^^^^^^^
```
Em chạy thử `train_per_iter()` ở file `train.py`  do khi em train model trên Kaggle thì em thấy lỗi ở phần đấy
Em nghĩ là có khả năng nó liên quan đến `CustomDataset` do output em để ở file đó nó là `Dict` nhưng khi em lấy output của nó ra thì em lại lấy theo kiểu `panda.Series`. 
Đây là code em thử

```
model = T5ForConditionalGeneration.from_pretrained(model_params['MODEL'])
model = model.to(DEVICE)
optimizer = torch.optim.Adam(model.parameters(), lr=model_params['LEARNING_RATE'])
loss = train_per_iter(model, '\data\Review_Comment_Generation\t5_data\train.jsonl', optimizer= optimizer)
print(loss)
```

**Comment by manhtdd** [comment]
Nếu như lỗi của e nằm ở `train_per_iter()` thì e cần phải cung cấp thêm cho a cả code của `train_per_iter()` nữa.

**Comment by manhtdd** [comment]
Với cả sao cái bug của e lại thiếu thông tin vậy nhỉ? Cái output a nghĩ nó phải có nhiều thông tin hơn thế kia chứ.

**Comment by Bonkaaa** [comment]
Đây là toàn bộ phần bug.
```
Traceback (most recent call last):
  File "D:\Neutral_network\Code_review_generation\train\train.py", line 117, in <module>
    loss = train_per_iter(model, '\data\Review_Comment_Generation\t5_data\train.jsonl', optimizer= optimizer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Neutral_network\Code_review_generation\train\train.py", line 17, in train_per_iter
    in_ids = data['source_ids'].to(DEVICE)
             ~~~~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```
Em nghĩ là khả năng là ở `train_per_iter()` của em chỗ vòng for có vẻ gặp lỗi, cụ thể hơn là đoạn `data`
Đây là hàm `train_per_iter()`
```
def train_per_iter(model, train_set_loader, optimizer):
    # Initialize variables
    total_loss = 0

    for i, data in enumerate(train_set_loader):
        # Extracting data
        in_ids = data['source_ids'].to(DEVICE)
        in_mask = data['source_mask'].to(DEVICE)
        target_ids = data['target_ids'].to(DEVICE)

        # Clear cache
        optimizer.zero_grad()

        # forward
        outputs = model(
            input_ids=in_ids,
            attention_mask=in_mask,
            decoder_input_ids=target_ids,
        )

        loss = outputs.loss

        # update loss
        total_loss += loss.item()

        # backward
        loss.backward()

        # Update parameters
        optimizer.step()

    final_loss = total_loss / len(train_set_loader)
    return final_loss
```
Còn đây là phần `CustomDataset`
```
from torch.utils.data import Dataset
from preprocessing import *

# CustomDataset
class CustomDataset(Dataset):
    def __init__(self, path, tokenizer, code_lines_len, comments_len):
        """
        Initializes Dataset class

        :param path: where data locates
        :param tokenizer: Transformer tokenizer
        :param code_lines_len: max length of codes
        :param comments_len: max length of comments\
        """

        self.data = data(path)
        self.code_lines = self.data['Code_tokens'].tolist()
        self.comments = self.data['Docstring_tokens'].tolist()
        self.tokenizer = tokenizer
        self.code_lines_len = code_lines_len
        self.comments_len = comments_len

    def __len__(self):  # return the length
        return len(self.code_lines)

    def __getitem__(self, idx):
        code = str(self.code_lines[idx])
        comment = str(self.comments[idx])

        # Tokenizer source and target
        source_encoding = self.tokenizer.encode(
            code,
            max_length=self.code_lines_len,
            padding='max_length',
            truncation=True,
            return_tensors='pt',
        )
        target_encoding = self.tokenizer.encode(
            comment,
            max_length=self.comments_len,
            padding='max_length',
            truncation=True,
            return_tensors='pt',
        )

        source_ids = source_encoding['input_ids'].squeeze()
        source_mask = source_encoding['attention_mask'].squeeze()
        target_ids = target_encoding['input_ids'].squeeze()

        return {
            'source_ids': source_ids,
            'source_mask': source_mask,
            'target_ids': target_ids,
        }
```
Theo em thấy thì phần output của `CustomDataset` của em đang là định dạng `dict`. Phần em lấy output ở `train_per_iter()` cũng là dict nhưng bug hiện lên là index của `dict` phải là `int` trong khi output em để là `dict` thì index là `string` . Phần này em cũng chưa rõ. Mong anh xem em có gặp vấn đề gì không ạ

**Comment by manhtdd** [comment]
`DataLoader` của em đâu nhỉ? Nếu dùng class `Dataset` của `torch` thì phải đi kèm `DataLoader` chứ?

**Comment by manhtdd** [comment]
> `DataLoader` của em đâu nhỉ? Nếu dùng class `Dataset` của `torch` thì phải đi kèm `DataLoader` chứ?

Ok, a thấy `DataLoader` của em rồi. A nghĩ em nên in cái biến `data` ở dùng 17 của file `train.py` ra, xem nó trông như nào, `type()` trả về gì.

**Comment by manhtdd** [comment]
Với cả chuẩn bị cho a cả `README.md` cho repo này, trong đấy nên bao gồm cách cài đặt để chạy repo này, để anh còn chạy test cho em.

**Comment by Bonkaaa** [comment]
> > `DataLoader` của em đâu nhỉ? Nếu dùng class `Dataset` của `torch` thì phải đi kèm `DataLoader` chứ?
> 
> Ok, a thấy `DataLoader` của em rồi. A nghĩ em nên in cái biến `data` ở dùng 17 của file `train.py` ra, xem nó trông như nào, `type()` trả về gì.

Em đã thử lại và nhận ra một điều ra code em thử nó sai do em để `path` của `Dataset` thay vì `DataLoader` vào hàm `train_per_iter()`. Bây giờ em thử lại thì nó gặp bug khác liên quan đến tensor bắt nguồn từ file `CustomDataset`
🐛 Đây là bug ạ
```
<ipython-input-8-112cfa3b9644> in __getitem__(self, idx)
     44         )
     45 
---> 46         source_ids = source_encoding['input_ids'].squeeze()
     47         source_mask = source_encoding['attention_mask'].squeeze()
     48         target_ids = target_encoding['input_ids'].squeeze()

IndexError: too many indices for tensor of dimension 2
```
Em đang nghĩ là khả năng `squeeze()` xóa nhầm phải non-existed dimension của tensor nên nó báo lỗi. Chắc là em phải kiểm tra lại dimension của các tensor này ạ 🚧
Đây là code của CustomDataset
```
from torch.utils.data import Dataset
from preprocessing import *

# CustomDataset
class CustomDataset(Dataset):
    def __init__(self, path, tokenizer, code_lines_len, comments_len):
        """
        Initializes Dataset class

        :param path: where data locates
        :param tokenizer: Transformer tokenizer
        :param code_lines_len: max length of codes
        :param comments_len: max length of comments\
        """

        self.data = data(path)
        self.code_lines = self.data['Code_tokens'].tolist()
        self.comments = self.data['Docstring_tokens'].tolist()
        self.tokenizer = tokenizer
        self.code_lines_len = code_lines_len
        self.comments_len = comments_len

    def __len__(self):  # return the length
        return len(self.code_lines)

    def __getitem__(self, idx):
        code = str(self.code_lines[idx])
        comment = str(self.comments[idx])

        # Tokenizer source and target
        source_encoding = self.tokenizer.encode(
            code,
            max_length=self.code_lines_len,
            padding='max_length',
            truncation=True,
            return_tensors='pt',
        )
        target_encoding = self.tokenizer.encode(
            comment,
            max_length=self.comments_len,
            padding='max_length',
            truncation=True,
            return_tensors='pt',
        )

        source_ids = source_encoding['input_ids'].squeeze()
        source_mask = source_encoding['attention_mask'].squeeze()
        target_ids = target_encoding['input_ids'].squeeze()

        return {
            'source_ids': source_ids,
            'source_mask': source_mask,
            'target_ids': target_ids,
        }

```

**Comment by manhtdd** [comment]
Cách debug hiệu quả nhất mà liên quan đến chiều của tensor là in cái `shape/size` của nó ra thôi. Còn CustomDataset của em a thấy ko có vấn đề gì.

**Comment by Bonkaaa** [comment]
Hello anh. Hôm nay em học cả ngày nên giờ mới fix lỗi ạ. Hmm em nhận ra vấn đề nó nằm ở chỗ `tokenizer_encode`. Function này nó không sinh ra `attention mask` nên nó sinh ra bug, bug không nằm ở `squeeze()` ạ. Nên là em đã sửa thành `tokenizer_encode_plus`. Nó có vẻ chạy được anh ạ.

![image](https://github.com/user-attachments/assets/778d91ed-3201-46a8-be50-48ff4806b81e)

Tự dưng em gặp lỗi này. Em không biết kaggle có giới hạn memory sử dụng không. Có gì mai em sửa tiếp ạ. Em báo cáo qua với anh như thế ạ
